Added utf8 encoding header.
0a8dfb890f9e introduced non-ascii characters in the source file, causing:

    SyntaxError: Non-ASCII character '\xe2' in file data_hacks/histogram.py on line 188, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details